Repository fga-gpp-mds/2018.1-Lacos-da-Alegria-API, pull requests merged in 2018-06, with the labels that each got.

#13 Refined user validation
  lacos_api/user_api/models.py
  lacos_api/user_api/tests_user/test_urls.py
Labels: bug, development team

#14 Implemented Restful
  lacos_api/activity_api/serializers.py
  lacos_api/activity_api/urls.py
  lacos_api/user_api/serializers.py
  lacos_api/user_api/urls.py
Labels: development team, important

#9 Created Ngo activities
  .pytest_cache/v/cache/lastfailed
  .pytest_cache/v/cache/nodeids
  config/db.sqlite3
  lacos_api/activity_api/admin.py
  lacos_api/activity_api/migrations/0001_initial.py
  lacos_api/activity_api/models.py
  lacos_api/activity_api/serializers.py
  lacos_api/activity_api/test_hospital_activity/__init__.py
  lacos_api/activity_api/test_hospital_activity/factories.py
  lacos_api/activity_api/test_hospital_activity/test_admin.py
  lacos_api/activity_api/test_hospital_activity/test_models.py
  lacos_api/activity_api/test_hospital_activity/test_urls.py
  lacos_api/activity_api/test_hospital_activity/test_views.py
  lacos_api/activity_api/test_ngo_activity/__init__.py
  lacos_api/activity_api/test_ngo_activity/factories.py
  lacos_api/activity_api/test_ngo_activity/test_admin.py
  lacos_api/activity_api/test_ngo_activity/test_models.py
  lacos_api/activity_api/test_ngo_activity/test_urls.py
  lacos_api/activity_api/test_ngo_activity/test_views.py
  lacos_api/activity_api/views.py
  lacos_api/general/urls.py
  lacos_api/user_api/migrations/0001_initial.py
  lacos_api/user_api/models.py
  lacos_api/user_api/urls.py
  lacos_api/user_api/views.py
Labels: development team, important, medium, review, user story

#17 Feature/#216 subscription activity
  lacos_api/user_api/views.py
Labels: development team, important

#20 Bug fix/acceptance criteria
  lacos_api/activity_api/views.py
Labels: development team

#19 Created novice queue
  config/db.sqlite3
  lacos_api/activity_api/migrations/0001_initial.py
  lacos_api/activity_api/migrations/0002_auto_20180617_2248.py
  lacos_api/activity_api/models.py
  lacos_api/activity_api/serializers.py
  lacos_api/activity_api/views.py
  lacos_api/user_api/migrations/0001_initial.py
Labels: development team, important, review

#24 Added ngo functionalities
  config/db.sqlite3
  lacos_api/activity_api/migrations/0001_initial.py
  lacos_api/activity_api/migrations/0002_auto_20180623_0121.py
  lacos_api/activity_api/models.py
  lacos_api/activity_api/serializers.py
  lacos_api/activity_api/views.py
  lacos_api/user_api/migrations/0001_initial.py
  lacos_api/user_api/migrations/0002_userprofile_inscrito.py
  lacos_api/user_api/views.py
Labels: development team, help wanted, important, review

#27 Tests
  lacos_api/activity_api/test_hospital_activity/test_views.py
  lacos_api/activity_api/test_ngo_activity/test_views.py
  lacos_api/activity_api/views.py
  lacos_api/user_api/tests_user/test_views.py
  lacos_api/user_api/views.py
Labels: development team, important

#28 Added comments in view of activity api.
  lacos_api/activity_api/views.py
Labels: development team, important
